### ISSUE TITLE
Setup Travis CI

### ISSUE THREAD

**Issue by perfectmak** [ilaboauife/voucher-service#11]
Setup Travis for automated builds and tests

**Comment by goodnesskay** [comment]
I have worked on the Travis continuous integration and the code passes the test with php 7.1 but does not pass the test with lesser versions of php. So, I removed the lesser versions of php in the .travis.yml file

**Comment by perfectmak** [comment]
Yes, that is cool. We are currently using only php 7.1 core features, so it is bound to break on lesser version. Nice job 👍

**Comment by goodnesskay** [comment]
Thanks
